{
 "title": "Kubernetes / Events / Overview",
 "description": "A dashboard that monitors Kubernetes Events and focuses on giving a overview for events. It is created using the [kubernetes-events-mixin](https://github.com/adinhodovic/kubernetes-events-mixin). A pre requisite is configuring Loki, Alloy and Prometheus - it is described in this blog post: https://hodovi.cc/blog/kubernetes-events-monitoring-with-loki-alloy-and-grafana/",
 "tags": [
  "kubernetes",
  "kubernetes-events",
  "kubernetes-events-mixin"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "kind",
    "label": "Kind",
    "query": "label_values(namespace_kind_type:kubernetes_events:count1m{}, k8s_resource_kind)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(namespace_kind_type:kubernetes_events:count1m{k8s_resource_kind=\"$kind\"}, k8s_namespace_name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary All Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events",
   "type": "timeseries",
   "description": "Total Event Emissions by Kind and Namespace[1w]",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(namespace_kind_type:kubernetes_events:count1m{}) by (k8s_resource_kind, k8s_namespace_name, type)\n",
     "legendFormat": "{{k8s_resource_kind}} / {{k8s_namespace_name}} / {{type}}"
    }
   ]
  },
  {
   "title": "Top 10 Normal Event Emissions by Kind and Namespace[1w]",
   "type": "table",
   "description": "Top 10 Normal Event Emissions by Kind and Namespace[1w]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time(namespace_kind_type:kubernetes_events:count1m{type=\"Normal\"}[1w])) by (k8s_resource_kind, k8s_namespace_name))\n"
    }
   ]
  },
  {
   "title": "Top 10 Warning Event Emissions by Kind and Namespace[1w]",
   "type": "table",
   "description": "Top 10 Warning Event Emissions by Kind and Namespace[1w]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time(namespace_kind_type:kubernetes_events:count1m{type=\"Warning\"}[1w])) by (k8s_resource_kind, k8s_namespace_name))\n"
    }
   ]
  },
  {
   "title": "Kind Summary ($kind / $namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Events by Type[1w]",
   "type": "piechart",
   "description": "Events by Type[1w]",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(namespace_kind_type:kubernetes_events:count1m{k8s_resource_kind=\"$kind\", k8s_namespace_name=\"$namespace\"}[1w])) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Events by Type",
   "type": "timeseries",
   "description": "Events by Type",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(namespace_kind_type:kubernetes_events:count1m{k8s_resource_kind=\"$kind\", k8s_namespace_name=\"$namespace\"}) by ( type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}